language: node_js
node_js:
  - '12'
cache:
  directories:
    - node_modules
services:
  - mysql
  - redis-server
env:
  global:
    - CC_TEST_REPORTER_ID=6f27ef5d6de82b5f7d030bee632fc1579f3604a66c01fc142e0bc0a55ec7bb10
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_install:
  - mysql -e 'CREATE DATABASE ecommerce_test;'
install:
  - npm install
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
