language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
services:
  - mysql
  - redis-server
env:
  global:
    - CC_TEST_REPORTER_ID=CC_TEST_REPORTER_ID
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_install:
  - mysql -e 'CREATE DATABASE e_commerce_test;'
install:
  - npm install
script:
  - npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
